// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Phone    string `form:"phone"`    // user_name
	Password string `form:"password"` //  password
}

type LoginRes struct {
	Result Result `json:"result"`
	Token  string `json:"token"` // jwt token for api
	User   User   `json:"user"`  // Account info
}

type RegisterReq struct {
	Phone    string `form:"phone"`
	Password string `form:"password"`
	UserRole int64  `form:"user_role"`
}

type RegisterRes struct {
	Result Result `json:"result"`
	Token  string `json:"token"` // jwt token for api
	User   User   `json:"user"`  // Account info
}

type GetUserReq struct {
	UserID int64 `form:"user_id,optional"`
}

type GetUserRes struct {
	Result Result `json:"result"`
	User   User   `json:"user"`
}

type UpdateUserReq struct {
	UserID      int64  `path:"id"`
	Password    string `form:"password,optional"`
	FullName    string `form:"fullName,optional"`
	Birthday    int64  `form:"birthday,optional"`
	Address     string `form:"address,optional"`
	AvatarUrl   string `form:"avatarUrl,optional"`
	Gender      int64  `form:"gender,optional"`
	CccdNumber  string `form:"cccdNumber,optional"`
	CccdDate    int64  `form:"cccdDate,optional"`
	CccdAddress string `form:"cccdAddress,optional"`
}

type UpdateUserRes struct {
	Result Result `json:"result"`
	User   User   `json:"user"` // Account info
}

type ChangePasswordReq struct {
	OldPassword string `form:"old_password"`
	NewPassword string `form:"new_password"`
}

type ChangePasswordRes struct {
	Result Result `json:"result"`
}

type UploadFileReq struct {
	UploadType int    `form:"upload_type"`
	FileName   string `form:"file_name"`
}

type UploadFileRes struct {
	Result    Result `json:"result"`
	AvatarUrl string `json:"avatar_url"`
}

type FilterUserReq struct {
	SearchPhone string `form:"searchPhone,optional"`
	Limit       int64  `form:"limit,optional"`
	Offset      int64  `form:"offset,optional"`
}

type FilterUserRes struct {
	Result Result `json:"result"`
	Users  []User `json:"users"`
}

type Result struct {
	Code    int    `json:"code"`    //    Result code: 0 is success. Otherwise, getting an error
	Message string `json:"message"` // Result message: detail response code
}

type User struct {
	UserID      int64  `json:"userID"`
	Phone       string `json:"phone"`
	Role        int64  `json:"role"`
	Status      int64  `json:"status"`
	Address     string `json:"address"`
	FullName    string `json:"fullName"`
	AvatarUrl   string `json:"avatarUrl"`
	Birthday    int64  `json:"birthday"`
	Gender      int64  `json:"gender"`
	CccdNumber  string `json:"cccdNumber"`
	CccdDate    int64  `json:"cccdDate"`
	CccdAddress string `json:"cccdAddress"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type House struct {
	HouseID     int64     `json:"houseID"`
	User        User      `json:"user"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        int64     `json:"type"`
	Status      int64     `json:"status"`
	Area        int64     `json:"area"`
	Price       int64     `json:"price"`
	BedNum      int64     `json:"bedNum"`
	LivingNum   int64     `json:"livingNum"`
	Albums      []string  `json:"albums"`
	Rooms       []Room    `json:"rooms"`
	Services    []Service `json:"services"`
	Address     string    `json:"address"`
	WardID      int64     `json:"wardID"`
	DistrictID  int64     `json:"districtID"`
	ProvinceID  int64     `json:"provinceID"`
	CreatedAt   int64     `json:"createdAt"`
	UpdatedAt   int64     `json:"updatedAt"`
	CreatedBy   int64     `json:"createdBy"`
	UpdatedBy   int64     `json:"updatedBy"`
}

type Album struct {
	AlbumID int64  `json:"albumID"`
	HouseID int64  `json:"houseID"`
	Url     string `json:"url"`
}

type Room struct {
	RoomID    int64  `json:"roomID"`
	HouseID   int64  `json:"houseID"`
	Name      string `json:"name"`
	HouseName string `json:"houseName"`
	Area      int64  `json:"area"`
	Price     int64  `json:"price"`
	Type      int64  `json:"type"`
	Status    int64  `json:"status"`
	Capacity  int64  `json:"capacity"`
	EIndex    int64  `json:"eIndex"`
	WIndex    int64  `json:"wIndex"`
}

type Service struct {
	ServiceID int64  `json:"serviceID"`
	HouseID   int64  `json:"houseID"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Unit      int64  `json:"unit"`
}

type Contract struct {
	ContractID    int64   `json:"contractID"`
	Code          string  `json:"code"`
	Status        int64   `json:"status"`
	RenterID      int64   `json:"renterID"`
	RenterPhone   string  `json:"renterPhone"`
	RenterNumber  string  `json:"renterNumber"`
	RenterDate    int64   `json:"renterDate"`
	RenterAddress string  `json:"renterAddress"`
	RenterName    string  `json:"renterName"`
	LessorID      int64   `json:"lessorID"`
	LessorPhone   string  `json:"lessorPhone"`
	LessorNumber  string  `json:"lessorNumber"`
	LessorDate    int64   `json:"lessorDate"`
	LessorAddress string  `json:"lessorAddress"`
	LessorName    string  `json:"lessorName"`
	Room          Room    `json:"room"`
	CheckIn       int64   `json:"checkIn"`
	Duration      int64   `json:"duration"`
	Purpose       string  `json:"purpose"`
	Payment       Payment `json:"payment"`
	CreatedAt     int64   `json:"createdAt"`
	UpdatedAt     int64   `json:"updatedAt"`
	CreatedBy     int64   `json:"createdBy"`
	UpdatedBy     int64   `json:"updatedBy"`
}

type PaymentRenter struct {
	ID        int64  `json:"id"`
	PaymentID int64  `json:"paymentID"`
	RenterID  int64  `json:"renterID"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
}

type PaymentDetail struct {
	ID        int64  `json:"id"`
	PaymentID int64  `json:"paymentID"`
	Name      string `json:"name"`
	Price     int64  `json:"price"`
	Type      int64  `json:"type"`
}

type Payment struct {
	PaymentID      int64           `json:"paymentID"`
	ContractID     int64           `json:"contractID"`
	Amount         int64           `json:"amount"`
	Discount       int64           `json:"discount"`
	Deposit        int64           `json:"deposit"`
	DepositDate    int64           `json:"depositDate"`
	NextBill       int64           `json:"nextBill"`
	PaymentRenters []PaymentRenter `json:"paymentRenters"`
	PaymentDetails []PaymentDetail `json:"paymentDetails"`
}

type Bill struct {
	BillID       int64        `json:"billID"`
	Title        string       `json:"title"`
	ContractCode string       `json:"contractCode"`
	PaymentID    int64        `json:"paymentID"`
	PaymentDate  int64        `json:"paymentDate"`
	Amount       int64        `json:"amount"`
	Remain       int64        `json:"remain"`
	Status       int64        `json:"status"`
	BillDetails  []BillDetail `json:"billDetails"`
}

type BillDetail struct {
	BillDetailID int64  `json:"billDetailID"`
	BillID       int64  `json:"billID"`
	Name         string `json:"name"`
	Price        int64  `json:"price"`
	Type         int64  `json:"type"`
	Quantity     int64  `json:"quantity"`
}

type BillPay struct {
	BillPayID int64 `json:"billPayID"`
	BillID    int64 `json:"billID"`
	Amount    int64 `json:"amount"`
	PayDate   int64 `json:"payDate"`
	UserID    int64 `json:"userID"`
}
