// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"roomrover/service/inventory/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadFileHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/house",
					Handler: CreateHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/house/filter",
					Handler: FilterHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/house/:id",
					Handler: GetHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/house/:id/status",
					Handler: UpdateHouseStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/house/:id",
					Handler: UpdateHouseHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/house/:id",
					Handler: DeleteHouseHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/invent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/house/search",
				Handler: SearchHouseHandler(serverCtx),
			},
		},
		rest.WithPrefix("/invent"),
	)
}
